// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ODBLSDXQF4zk1bvg-lxBFaRdjVHKZRI',
    appId: '1:323967754756:web:7ea8b83b09210b87ce0b51',
    messagingSenderId: '323967754756',
    projectId: 'bouek-ebd45',
    authDomain: 'bouek-ebd45.firebaseapp.com',
    storageBucket: 'bouek-ebd45.firebasestorage.app',
    measurementId: 'G-12X9C36ZEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaR-73SZJ3OMbnCKNFDY4PuKbNroQx7ag',
    appId: '1:323967754756:android:fc51a712ec516b0fce0b51',
    messagingSenderId: '323967754756',
    projectId: 'bouek-ebd45',
    storageBucket: 'bouek-ebd45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAMxmOkchIgjraZKDJSk95krDA9FzXLrA',
    appId: '1:323967754756:ios:764c76caebb73af7ce0b51',
    messagingSenderId: '323967754756',
    projectId: 'bouek-ebd45',
    storageBucket: 'bouek-ebd45.firebasestorage.app',
    iosClientId: '323967754756-bvkt11j11tes1t7mljoqcb9egip2utn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bouek',
  );
}
